version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app-be
    image: oven/bun:slim
    environment:
      - PORT=8080
      - NODE_ENV=production
    ports:
      - "5000:8080"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["bun", "run", "dev"]
